services:
  # Backend API Service
  - type: web
    name: plate-scanner-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node backend\server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false  
      - key: MAILTRAP_TOKEN
        sync: false
      - key: CLIENT_URL
        Value: https://plate-scanner-api.onrender.com
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: plate-scanner-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /landing-page.html